version = 0.1
[default.global.parameters]
stack_name = "aws-app-composer-basic-api"
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
stack_name = "ab-dev-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hsm77ga61yqi"
s3_prefix = "ab-dev-api"
region = "us-east-1"
profile = "abcarmody"
image_repositories = []