version = 0.1
[default.global.parameters]
stack_name = "aws-app-composer-basic-api"
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "ab-dev-log"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hsm77ga61yqi"
s3_prefix = "ab-dev-log"
region = "us-east-1"
profile = "abcarmody"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true

[stage]
[stage.deploy]
[stage.deploy.parameters]
stack_name = "ab1-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hsm77ga61yqi"
s3_prefix = "ab1-stack"
region = "us-east-1"
profile = "abcarmody"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
